[[race]]
name = "1/8 Mile Dig"
start_mph = 0.0
target_distance_ft = 660.0

[[race]]
name = "1/4 Mile Dig"
start_mph = 0.0
target_distance_ft = 1320.0

[[race]]
name = "1 Mile Dig"
start_mph = 0.0
target_distance_ft = 5280.0

[[race]]
name = "40-150 mph Roll"
start_mph = 40.0
target_speed_mph = 150.0

[[race]]
name = "60-150 mph Roll"
start_mph = 60.0
target_speed_mph = 150.0
